config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  get "/ask", to: "questions#ask"
  get "/answer", to: "questions#answer"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def ask
    # emtpy
  end

  def answer
    @question = params[:question]

    if @question.nil?
      @answer = "Please ask a question"
    elsif @question.downcase == "hello"
      @answer = "hello too"
    elsif @question.downcase == "what time is it?"
      @answer = Time.now.strftime("%I:%M:%S %p")
    elsif @question == "I am going to work"
      @answer = "Great!"
    elsif @question.end_with?("?")
      @answer = "Silly question, get dressed and go to work!"
    else
      @answer = "I don't care, get dressed and go to work!"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStupidCoaching</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/answer.html.erb
<%# display question as well as answer %>
<div class="chat-container col-4">
  <h1>Stupid Coaching</h1>
  <div class="question">
    <p id="displayedquestion"><%= @question %></p>
    <p><em>- You</em></p>
  </div>
  <div class="answer">
    <p id="displayedanswer"><%= @answer %></p>
    <p><em>- Your coach</em></p>
  </div>
  <%= link_to 'Ask another question', ask_path(question: @question) %>
</div>

app/views/questions/ask.html.erb
<div class="col-4" id="formblock">
  <h1>Stupid Coaching</h1>
  <form action="/answer" data-turbo="false" method="get">
    <label for="question">Ask your coach anything:</label>
    <div class="d-flex">
      <input type="text" class="form-control" name="question" id="question" placeholder="Write your questions here" value="<%= params[:question] %>">
      <button type="submit" class="btn btn-primary" id="button">Ask!</button>
    </div>
  </form>
  <%= link_to 'See answer', answer_path %>
</div>